import { fieldsProxy } from "@serenity-is/corelib/q";

export interface FullProfileRow {
    Id?: number;
    DivisionId?: number;
    OccupationId?: number;
    DepartmentId?: number;
    SectionId?: number;
    EmployeeName?: string;
    EmployeeId?: string;
    Nric?: string;
    Age?: number;
    LastPaymentDate?: string;
    RecruitmentDate?: string;
    Birthday?: string;
    EmployeeEmail?: string;
    EpfAccountNumber?: string;
    ProbationPeriod?: number;
    NoticePeriod?: number;
    Address?: string;
    TelNumber1?: string;
    TelNumber2?: string;
    PassportNumber?: string;
    PassportIssueDate?: string;
    PassportValidPeriod?: number;
    PassportExpiryDate?: string;
    BonusFactor?: number;
    BasicSalary?: number;
    InsertDate?: string;
    UpdateDate?: string;
    DeleteDate?: string;
    RaceId?: number;
    EmployeeType?: number;
    Sex?: number;
    IsActive?: number;
    InsertUserId?: number;
    UpdateUserId?: number;
    DeleteUserId?: number;
    JobGradeId?: number;
    BankId?: number;
    BankAccountNumber?: string;
    CityId?: number;
    StateId?: number;
    EmployeeImg?: string;
    NationalityId?: number;
    MaritalStatus?: number;
    GrantHrPrivilege?: number;
    CreateUser?: number;
    PayByHour?: number;
    PayByMonth?: number;
    PayByDay?: number;
    OtPayEntitlement?: number;
    UserPassword?: string;
    UserRowId?: number;
    UserName?: string;
    ResignationDate?: string;
    TerminateDate?: string;
    ResignLeaveDate?: string;
    TerminateLeaveDate?: string;
    Terminated?: number;
    Resigned?: number;
    RetireDate?: string;
    Retired?: number;
    WorkingSpouse?: number;
    ChildrenUnderEighteen?: number;
    ChildrenInUniversity?: number;
    PostalCode?: string;
    CountryId?: number;
    SocsoClass?: number;
    SocsoAccountNumber?: string;
    EpfClass?: number;
    EisClass?: number;
    CostCentreId?: number;
    WorkingPermit?: string;
    ArrivalDate?: string;
    WorkingPermitIssueDate?: string;
    WorkingPermitExpireDate?: string;
    WorkingPermitValidFrom?: string;
    WorkingPermitValidUntil?: string;
    ProbationPeriodFrom?: string;
    ProbationPeriodUntil?: string;
    PassedProbation?: number;
    Cp8dId?: number;
    PcBnumber?: string;
    SsfwEffectiveDate?: string;
    JobDescription?: string;
    DisabledChildInUniversity?: number;
    DisabledChild?: number;
    FixedOtRateOption?: number;
    OtRateWeekday?: number;
    OtRateWeekend?: number;
    OtRatePublicHoliday?: number;
    DailyWorkingMinute?: number;
    NightShiftAllowancePerDay?: number;
    HrdfClass?: number;
    OldNric?: string;
    SsfwNumber?: string;
    JoinDate?: string;
    DivisionName?: string;
    OccupationName?: string;
    DepartmentName?: string;
    SectionName?: string;
    Race?: string;
    JobGradeName?: string;
    BankName?: string;
    CityName?: string;
    StateName?: string;
    NationalityName?: string;
}

export abstract class FullProfileRow {
    static readonly idProperty = 'Id';
    static readonly nameProperty = 'EmployeeName';
    static readonly localTextPrefix = 'OrganisationChart.FullProfile';
    static readonly deletePermission = '*';
    static readonly insertPermission = '*';
    static readonly readPermission = '*';
    static readonly updatePermission = '*';

    static readonly Fields = fieldsProxy<FullProfileRow>();
}